services:
    marttiphpbb.calendartag.listener:
        class: marttiphpbb\calendartag\event\listener
        arguments:
            - '@marttiphpbb.calendartag.render'
            - '@marttiphpbb.calendartag.store'
        tags:
            - { name: event.listener }

    marttiphpbb.calendartag.store:
        class: marttiphpbb\calendartag\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.calendartag.render:
        class: marttiphpbb\calendartag\service\render
        arguments:
            - '@dispatcher'
            - '@marttiphpbb.calendartag.store'
            - '@language'
            - '@user'
